name = "Pixelfy"
license = "MIT"
licenselink = "https://github.com/TakWolf/hugo-theme-pixelfy/blob/master/LICENSE"
description = "A pixel style Hugo theme"
homepage = "https://github.com/TakWolf/hugo-theme-pixelfy"
demosite = "https://hugo-theme-pixelfy.takwolf.com"
tags = ["blog", "pixel"]
features = ["blog", "pixel"]

[author]
name = "TakWolf"
homepage = "https://takwolf.com"
